apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmsearchindex
  namespace: llmsearchindex
  labels:
    app: llmsearchindex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llmsearchindex
  template:
    metadata:
      labels:
        app: llmsearchindex
    spec:
      containers:
      - name: llmsearchindex
        image: quay.io/aicatalyst/llmsearchindex:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        env:
        - name: HF_HOME
          value: /tmp/hf_cache
        resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
